### ISSUE TITLE
Keybinding issue on latest version

### ISSUE THREAD

**Issue by Skolig** [retrospy/RetroSpy#138]
Tried a variety of key/button combinations but without exception when I trigger those keybinds I get the error 

`Could not load type 'InputUnion' from assembly 'Retrospy, Version=3.7.0.0, Culture=neutral, PublicKeyToken=null' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.`

For what it's worth, my `keybindings.xml` file currently looks like

```xml
<?xml version="1.0" encoding="UTF-8"?>
<keybindings>
    <binding output-key="home">
        <input button="z" />
    </binding>
</keybindings>
```

This is for a GameCube controller. The input display is otherwise fine.

**Comment by zoggins** [comment]
That is an interesting one, I will take a look.  Thanks!

**Comment by zoggins** [comment]
Good news! I can reproduce the problem.  Bad news!  I have no idea what is
wrong.  I will sort it out.

**Comment by zoggins** [comment]
I think I found the problem.  There is a bigger issue I have to solve, but this stop gap release should be working.

https://retro-spy.com/download/RetroSpy-release.zip

Let me know if it works or not. Thanks!

**Comment by Skolig** [comment]
It works, the only issue I have now is that the delay variable also affects keybinds, ideally I'd use the keybinds to control my timer but I use the delay feature within RetroSpy to account for the input introduced by my video capture.

**Comment by zoggins** [comment]
Interesting.  I am trying to think through what that would look like.  Let
me put some thought into it.

**Comment by zoggins** [comment]
Its a long shot, but I just uploaded a new version that might help your problem.  Not 100% sure, but let me know.

**Comment by Skolig** [comment]
Still behaving the same way; having the delay set to 1500ms causes keybindings to occur with the same delay instead of instantly.

**Comment by zoggins** [comment]
Ok, I will figure something out.

**Comment by zoggins** [comment]
It seems to be working for me. Maybe my upload was bad.  Let me upload it to github

**Comment by zoggins** [comment]
Yes it appears the old zip file is cached.  I will get it uncached after dinner, but on my end it appears to be working.

**Comment by zoggins** [comment]
https://github.com/retrospy/RetroSpy/releases/tag/v3.7.1

Try that.

**Comment by Skolig** [comment]
Yep, everything seems to be working perfectly now. Thanks!

**Comment by zoggins** [comment]
Awesome.  Glad I could help.  Let me know if you need anything else. Thanks!
