### ISSUE TITLE
Option to define custom skins path

### ISSUE THREAD

**Issue by edru** [retrospy/RetroSpy#148]
With the installer dropping RS into the C:\Programs Files it introduces some new "gotchas" for things.

1) Moving skins to the skins folder within the program files folder now requires elevated privileges to do so.
2) If reimaging a new machine it is now up to users to remember to back up all their skins elsewhere.

Could we get a way to define a skins path in the app? I like to keep all my layout/skins/stream stuff in 1 single folder so it can backup to the cloud and there isn't a way to do this in the current configuration.

**Comment by zoggins** [comment]
Good call.  Will add it.

Sent from Nine<http://www.9folders.com/>
________________________________
