### ISSUE TITLE
Nintendo SNES

### ISSUE THREAD

**Issue by 810munoz** [retrospy/RetroSpy#149]
Clean install of RetroSpy. Doesn't detect L, R, X, or A on Nintendo SNES input display.

((B, Y, Start, Select, and D-Pad all detect normally))

**Comment by zoggins** [comment]
Using 3.8 firmware and exe?  What skin are you using?  What you are describing is if there is NES firmware on your Arduino and you are trying to use it on an SNES.  I will double check, but I just test SNES myself and it was working fine.

**Comment by 810munoz** [comment]
Using default Nintendo SNES skin with ihaveonebigeye's input display set to SNES.

**Comment by 810munoz** [comment]
And you're right, it behaves the same way if I have it on SNES or NES setting. hmm...

**Comment by zoggins** [comment]
Nothing is jumping out, but I am looking into this.

**Comment by 810munoz** [comment]
I guess it could just be faulty hardware. I talked to ihaveonebigeye and he says he'll get started on a replacement. It's pretty weird since he tested it before shipping, but we'll see. Thanks for the super fast replies!

**Comment by zoggins** [comment]
Closing for now. Let me know if you have any other problems.
