### ISSUE TITLE
Does Retrospy for Switch work on Ethernet desktops?

### ISSUE THREAD

**Issue by PrinceKomali** [retrospy/RetroSpy#156]

**Comment by zoggins** [comment]
Not sure what you mean by Ethernet desktops.

**Comment by PrinceKomali** [comment]
Sorry about that (I was rushed)
I'm helping someone else setup RetroSpy and they stream on a desktop pc which can't connect to WiFi; he uses Ethernet. Could RetroSpy still work on that?

**Comment by zoggins** [comment]
The Beaglebone and PC just have to be on the same network, the PC can be wired and the beaglebone green can be wireless, or the PC can be wireless and the Beaglebone Black/Green can be wired.  They just have to be able to communicate with each other via IP address.
