### ISSUE TITLE
Settings are lost on upgrade

### ISSUE THREAD

**Issue by 40wattrange** [retrospy/RetroSpy#160]
During the upgrade to a new version it asks to uninstall the old version. When doing so it does leave all your custom skins in place, but it removes any settings you had so that when you re-launch after the upgrade you have to reconfigure it all again. 

It forgets:
what device you had selected
the port you selected, the skin you selected
which systems were set to be excluded from the view.
Possibly the delay time
Possibly hostname for devices that require IP

EDIT: Keybindings were removed as well.

**Comment by edru** [comment]
It seems that the uninstall during upgrade deleted the skin.ini file for my active skin too.

**Comment by zoggins** [comment]
Yeah,  that is a problem. ☹. Will take a look.

**Comment by zoggins** [comment]
This has been fixed.
