### ISSUE TITLE
RetroSpy has stopped working

### ISSUE THREAD

**Issue by codemann8** [retrospy/RetroSpy#164]
It's been awhile since I've updated RetroSpy, but the newest version doesn't load at all. It says RetroSpy has stopped working and closes immediately.

**Comment by zoggins** [comment]
Sorry to hear that.  Newest version?  And it immediately stops?  Did you download the installer or the .zip file?  Do you have .net framework 4.8 installed? Which windows version?  Sorry for all the questions, just want to narrow down the problem.


________________________________

**Comment by codemann8** [comment]
My apologies for the late reply. I found out it is crashing due to skins I had in there from previous versions. I'm not sure why it behaves differently with these but archiving them into another folder (until I find out the problem) fixes it.

**Comment by zoggins** [comment]
If you send me the offending skins, i can debug whats going on.  if that would help.

**Comment by zoggins** [comment]
Is this still an issue?

**Comment by zoggins** [comment]
closing from inactivity.  Feel free to repopen if necessary.
