### ISSUE TITLE
Analog Stick and digipad are swapped with a generic pc controller

### ISSUE THREAD

**Issue by MaggoLive** [retrospy/RetroSpy#165]
i got a generic pc controller with a digipad. When i use the generic pc skin (the xbox controller) the inputs from the digipad are shown as inputs of the left analog stick. Can i fix this by changing the code in the xml file?

**Comment by zoggins** [comment]
Sorry just seeing this.  I am not entirely sure the specific controller, but its highly likely you can change the skin.xml file for the PC controller skin.

**Comment by wertercatt** [comment]
> i got a generic pc controller with a digipad. When i use the generic pc skin (the xbox controller) the inputs from the digipad are shown as inputs of the left analog stick. Can i fix this by changing the code in the xml file?

A lot of generic PC controllers send their d-pads as 'analog' input. No idea why.

**Comment by 40wattrange** [comment]
This can be resolved by adjusting the skin file. This is not a bug of the application.

**Comment by zoggins** [comment]
If this is a still a problem what controller is it?

**Comment by zoggins** [comment]
closing from inactivity.  Feel free to repopen if necessary.
