### ISSUE TITLE
FYI, found the V1 GameBoyPrinterEmulator.cpp in your codebase is uncredited and not GPL v3.0 compliant and copyrighted to RetroSpy not arduino-gameboy-printer-emulator.

### ISSUE THREAD

**Issue by mofosyne** [retrospy/RetroSpy#172]
In https://github.com/retrospy/RetroSpy/blob/master/firmware/sketches/GameBoyPrinterEmulator.cpp#L35 found the code I written attributed to Christopher "Zoggins" Mallery in the main copyright header, using the MIT license header. Searching your readme or any contributor notes pages, I do not see any credit linking back to my project.

Requesting that it be noted as a wrapper over https://github.com/mofosyne/arduino-gameboy-printer-emulator and correctly attributed as being under `GNU General Public License v3.0` in both the readme and in the codebase.

And that the authors is myself Brian Khuu as well as contributors being from https://github.com/mofosyne/arduino-gameboy-printer-emulator#contributors--thanks . Please also note this in your licence and any relevant pages so people can discover the main codebase for this project.

https://github.com/mofosyne/arduino-gameboy-printer-emulator

Anyway I do think your project is pretty cool, but just want to make sure that these particulars is fixed to ensure that my work and others who helped with this project is credited correctly such as HerrZatacke, crizzlycruz, and others. It's a bad look if you simply copied and made no effort to link back to us in both the code and in the readme file.

------

e.g. For example xx0x was proactive and at least made a minimum best effort to credit us and link back to us.

https://github.com/xx0x/gbpxl#thanks

----

* https://github.com/retrospy/RetroSpy/commit/58b2a692d259c0e1510059b981c2b4dc42c857b8

**Comment by zoggins** [comment]
No offense was intended, will get it fixed.

**Comment by zoggins** [comment]
Should be better now.  If there is more you would like me to do just let me know.  I really meant offense, your project is awesome.

**Comment by mofosyne** [comment]
Yeah that's reasonable enough. It's not just a one-way benefit. Stuff like the https://github.com/mofosyne/arduino-gameboy-printer-emulator/blob/master/showcase/showcase.md showcase page also helps people to discover my stuff more via google searches as well as help foster a good community of people over at https://t.me/gameboycamera and other communities as well. Which means more contributions!

So no offense taken and hopefully you can join in on the fun.
