### ISSUE TITLE
Specific settings per type in skin.xml

### ISSUE THREAD

**Issue by 40wattrange** [retrospy/RetroSpy#174]
Would like to request a way to load/ignore specific settings in a skin config file.

Reasoning: 
Certain controllers conflict with each other - biggest culprit is that the Nintendo and Microsoft use the same letters, but on the opposite buttons.
Certain controllers are held differently, like when using a SNES controller for NES you wont be pressing B & A, youd press Y & B.
This would allow for a more universal skin setup.

Ideas: 

background and dpad assignments could be universal since they always match correctly

Create xml tags for the various types (PCGeneric, SNES, NES, GEN, etc) and within the tag is what is loaded when that specific type is selected, in addition to the universal stuff.

**Comment by 40wattrange** [comment]
I believe this was done, but I couldnt find the documentation that you gave me - if you still have it could you post it in the skins readme, or even here?

**Comment by zoggins** [comment]
Should be able to look at the wii-snes skin for how to do it.


________________________________
