### ISSUE TITLE
MiSTer multiple controller support

### ISSUE THREAD

**Issue by 40wattrange** [retrospy/RetroSpy#177]
Similar to how you can select various controllers in PC Generic, I would like to request teh ability to select from various controllers in MiSTer.

**Comment by zoggins** [comment]
This is probably possible, let me pull out the MiSTer and look.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: edru ***@***.***>
Sent: Thursday, March 11, 2021 10:42:10 AM
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] MiSTer multiple controller support (#177)


Similar to how you can select various controllers in PC Generic, I would like to request teh ability to select from various controllers in MiSTer.

**Comment by zoggins** [comment]
What exactly was the ask here?  Was this for selecting the controler ID?]

**Comment by 40wattrange** [comment]
This specific ask was ability to choose which controller to spy, similar to how you can with xinput 0-3 options. Gives you the ability to pick in case you have multiple controllers plugged in.

**Comment by zoggins** [comment]
Yes that should be in the latest release

**Comment by zoggins** [comment]
This is supported in the newest release.
