### ISSUE TITLE
MiSTer Multiplayer support

### ISSUE THREAD

**Issue by 40wattrange** [retrospy/RetroSpy#178]
In conjunction with supporting multiple controllers plugged in, it would be nice for MiSTer to send off commands if more than one controller was in use.

This way you could spawn multiple clients, have them select different controllers, and still work.

**Comment by zoggins** [comment]
I think this might actually work with the controller selector stuff I added.  I need to test this.

**Comment by 40wattrange** [comment]
I guess this would also play with the other issue I brought up - or may just be one in the same. If you had the ability to pick the controller being spied, then you could launch a 2nd instance and have it choose a different. Feel free to merge this request with the similar ask of controller selecting.

**Comment by zoggins** [comment]
This works in the next release.
