### ISSUE TITLE
N64 Firmware - Unsupported games

### ISSUE THREAD

**Issue by MrGamy** [retrospy/RetroSpy#179]
When running "Pokemon Snap" the Arduino is not able to capture any signals from the controller. In other games like "Super Mario 64" capturing works like a charm.
Are there any troubleshooting steps I could try or is this a general bug in the firmware?

I would be happy to supply any data to help fix the problem. I would need instructions though.

**Comment by zoggins** [comment]
Let me see if I can repro, my guess is that the game is doing something funny with the data packet and the Arduino doesn’t recognize it as controller data.  I just encountered this with Luigi’s Mansion the GameCube. Are you using the latest firmware (not that it should matter, just curious)?

From: MrGamy ***@***.***>
Sent: Thursday, March 25, 2021 10:53
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] N64 Firmware - Unsupported games (#179)


When running "Pokemon Snap" the Arduino is not able to capture any signals from the controller. In other games like "Super Mario 64" capturing works like a charm.
Are there any troubleshooting steps I could try or is this a general bug in the firmware?

I would be happy to supply any data to help fix the problem. I would need instructions though.

**Comment by MrGamy** [comment]
I am currently using the retrospy firmware v4.1

**Comment by zoggins** [comment]
I should be able to investigate this weekend, maybe tomorrow.  My guess is the packet header from the controller is different for Pokemon Snap (for whatever reason).  I am guessing it’s a relatively simple fix I just need to figure out the new header.

**Comment by MrGamy** [comment]
Take your time, no worries :-)
thanks for investigating! awesome project <3

**Comment by MrGamy** [comment]
Hey Zoggins, any update on the issue? Can you reproduce it?

**Comment by zoggins** [comment]
Sorry for the delay, I should be able to look at it soon. I haven’t forgotten about you, I promise. 😊

**Comment by MrGamy** [comment]
No worries! Sorry for poking. Your estimate sounded like a 5min lookup that's why I was following up.
I saw that you were working on retrospy over on discord - so I was wondering if you couldn't reproduce the problem.

**Comment by zoggins** [comment]
I can definitely repro.  I think I know what is going on, but I will need a few days to figure it out.

**Comment by MrGamy** [comment]
Thanks for letting me know! Otherwise I would have had to look at my arduino setup :-)

**Comment by zoggins** [comment]
Well there is a special place in hell for the hack I had to do to fix it, but I think I have it fixed.  I need to clean it up a bit, but I will release tomorrow.

**Comment by MrGamy** [comment]
:D I'd be super interested in what the problem was if you want to get into the details. :)
Thanks a lot for looking into this!

**Comment by zoggins** [comment]
Here is the update file if you want to beta test: https://github.com/retrospy/RetroSpy/blob/n64/firmware/sketches/N64.cpp

The long story short is the game seems to smash together a GetControllerInfo and a Controller Data Packet.  Usually it goes Header -> GetControllerInfo -> Header -> Controller Data, but this game seems to go Header -> GetControllerInfo -> Controller Data.  There is no second header, so I was completely throwing away the controller data packet.

**Comment by MrGamy** [comment]
Still works on Super Mario 64, still doesn't work with Pokemon Snap sadly just tried both

**Comment by zoggins** [comment]
Hmm, I probably broke something

**Comment by zoggins** [comment]
Sorry there was a bug in my refactor.  If you could try again, just to check.

**Comment by zoggins** [comment]
It shouldn’t have any more lag than on other games, but let me know if you see anything.

**Comment by MrGamy** [comment]
After some additional testing I noticed that it now works with my Gamecube Controller (via raphnet adapter) but not with my N64 controller (w/o Adapter)
I don't really know why.

**Comment by zoggins** [comment]
That is weird.  I only tested with the N64 controller directly to the N64.  I will double check my testing.  Trying to think why it would work with the adapter and not the controller directly.

**Comment by MrGamy** [comment]
I agree. It is very weird that it works with the GameCube Controller and 
not the original N64 controller. I was suspecting cable-lenght, but since I 
was able to play the game with the N64 controller I scraped that thought again.

**Comment by zoggins** [comment]
Do you have anything plugged into the controller (memory pak, rumble pak)?

**Comment by MrGamy** [comment]
Nope, nothing plugged in.
Same pattern as in the beginning though - Controller works in Super Mario 64.

**Comment by MrGamy** [comment]
Modded japanese n64 + RAM extension (oem)

**Comment by zoggins** [comment]
That’s what I have too.  I just retested and Pokemon Snap is definitely still working on my end.  I wanted to make sure I didn’t break something since I last tested.  Which version off of GitHub are you using?

**Comment by MrGamy** [comment]
I'm currently running the 4.2 pre-release from a week ago. But will try 4.2.3 as soon as I can
