### ISSUE TITLE
Ability to define custom images for diagonal inputs

### ISSUE THREAD

**Issue by 40wattrange** [retrospy/RetroSpy#182]
Trying to make a skin where the arcade stick just moves around. Can we get a way to define diagonal images so we dont have to show two images at once?

**Comment by zoggins** [comment]
I think what you are looking for already exists, but only for d-pads.  You want it for analog joysticks?  So when you move the joystick it lights up 1 of 8 buttons?

From: edru ***@***.***>
Sent: Tuesday, April 27, 2021 13:46
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] Ability to define custom images for diagonal inputs (#182)


Trying to make a skin where the arcade stick just moves around. Can we get a way to define diagonal images so we dont have to show two images at once?

**Comment by edru** [comment]
This would be for the digital dpad, not an analog stick. Did not know this already existed, awesome!

You have a link to the tags needed?

**Comment by zoggins** [comment]
"north", "northeast", "east", "southeast", "south", "southwest", "west", "northwest"

Should do it.

**Comment by 40wattrange** [comment]
Answer was provided above.
