### ISSUE TITLE
Seeing analog input (Stick or analog trigger) in digit output.

### ISSUE THREAD

**Issue by Robert-Ordis** [retrospy/RetroSpy#184]
Is there any way to see the input of analog stick / analog trigger in DIGIT OUTPUT ?

I need to see the input value in digit for setup the neutral position of the manual super swim in Legend of Zelda: The Wind Waker.

**Comment by zoggins** [comment]
So you want the analog sticks to show a button press on the input display?


________________________________
From: Robert_Ordis ***@***.***>
Sent: Saturday, June 12, 2021 18:43
To: retrospy/RetroSpy
Cc: Subscribed
Subject: [retrospy/RetroSpy] Seeing analog input (Stick or analog trigger) in digit output. (#184)


Is there any way to see the input of analog stick / analog trigger in DIGIT OUTPUT ?

I need to see the input value in digit for setup the neutral position of the manual super swim in Legend of Zelda: The Wind Waker.

**Comment by zoggins** [comment]
Oh I think I miss understood.  You want to see the actual number of the analog stick/trigger?


________________________________
From: Robert_Ordis ***@***.***>
Sent: Saturday, June 12, 2021 18:43
To: retrospy/RetroSpy
Cc: Subscribed
Subject: [retrospy/RetroSpy] Seeing analog input (Stick or analog trigger) in digit output. (#184)


Is there any way to see the input of analog stick / analog trigger in DIGIT OUTPUT ?

I need to see the input value in digit for setup the neutral position of the manual super swim in Legend of Zelda: The Wind Waker.

**Comment by Robert-Ordis** [comment]
yes

**Comment by zoggins** [comment]
I can probably put something together.  Let me see what I can do.

**Comment by Robert-Ordis** [comment]
Please.
I'm looking forward.

**Comment by zoggins** [comment]
I am starting work on this now, sorry for the wait.

**Comment by zoggins** [comment]
in the next release you will be able to do this:

<analogtext name="lstick_x" x="61" y="2" font="Arial" size="20" color="#FFFF00" range="100" />

that will represent the lstick (or whatever analog input) as a value -100 to 100 (in this case).  Obviously a trigger would be 0 to 100.  The scale can be changed with the range value.

**Comment by zoggins** [comment]
as shown above in 4.3

**Comment by Robert-Ordis** [comment]
Thanks a lot ! it works fine !
