### ISSUE TITLE
[Documentation Request] How to reverse engineer an unsupported controller?

### ISSUE THREAD

**Issue by wertercatt** [retrospy/RetroSpy#185]
I think documentation on how to figure out the signals of a currently unsupported controller would be very useful, as it would allow people who own more obscure and unsupported controllers to contribute to the project with their findings.

**Comment by zoggins** [comment]
That is a good idea.  I actually have two vtech kids “computers”  that I was going to reverse engineer, maybe I should document what I do. 😊  Is there a controller you had in mind?

From: Blaze Alan Marshall ***@***.***>
Sent: Thursday, July 8, 2021 13:37
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] [Documentation Request] How to reverse engineer an unsupported controller? (#185)


I think documentation on how to figure out the signals of a currently unsupported controller would be very useful, as it would allow people who own more obscure and unsupported controllers to contribute to the project with their findings.

**Comment by wertercatt** [comment]
I'm planning on eventually getting myself a Nuon, but I was also interested in reversing the signals of the currently unsupported Xbox controllers, such as the remote.

**Comment by wertercatt** [comment]
I'm also wondering if I could hook the Wii's Bluetooth adapter up to RetroSpy, as it communicates over a standard USB interface. This would potentially allow Wiimote input display, not just the extension controllers.
