### ISSUE TITLE
[Xbox] Add skin for the 'Controller S'

### ISSUE THREAD

**Issue by wertercatt** [retrospy/RetroSpy#188]
![image](https://user-images.githubusercontent.com/7116755/125406712-c119a580-e37e-11eb-8026-68686d8cab87.png)
Here's a high-quality image of a replica of the controller. That black part in the middle is the same logo as on the Duke on real examples.

**Comment by wertercatt** [comment]
![image](https://user-images.githubusercontent.com/7116755/126045441-58cc9afa-94a8-48f5-b958-de33f5237576.png)
Found a better image curtesy of the /r/originalxbox community

**Comment by zoggins** [comment]
That is a good one!  I will get a skin made of it.
