### ISSUE TITLE
AnalogText value: about output

### ISSUE THREAD

**Issue by Robert-Ordis** [retrospy/RetroSpy#197]
Is this output value a some kind of calculated value (-range to range)?
Is there any config to show RAW(as-is on shown from controller) value ?

**Comment by zoggins** [comment]
At the moment is 1 to -1.  I could probably throw something together to get the actual value which is typically a value between 0 and 255.  Let me see what I can do.

From: Robert_Ordis ***@***.***>
Sent: Saturday, August 28, 2021 21:58
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] AnalogText value: about output (#197)


Is this output value a some kind of calculated value (-range to range)?
Is there any config to show RAW(as-is on shown from controller) value ?

**Comment by zoggins** [comment]
this is fixed
