### ISSUE TITLE
MODE_DETECT Tutorial Update

### ISSUE THREAD

**Issue by Shentokk** [retrospy/RetroSpy#201]
I wanted to add a new mode for my firmware and I've completely forgotten how to do it the new way. The tutorial is still pretty out of date. Are there plans to update it?

**Comment by zoggins** [comment]
Yes, I should spend some time redoing this.  Thanks for the reminder

From: Shentokk ***@***.***>
Sent: Sunday, November 7, 2021 09:13
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] MODE_DETECT Tutorial Update (Issue #201)


I wanted to add a new mode for my firmware and I've completely forgotten how to do it the new way. The tutorial is still pretty out of date. Are there plans to update it?

**Comment by 40wattrange** [comment]
Not sure if this is still an issue - I believe this is how you do it now:

Enable the mode_detect in the primary firmware file as you would before
Then in the config_arduino.h file you can declare what analog pins are mapped to what system.

**Comment by zoggins** [comment]
Documentation should be up to date now
