### ISSUE TITLE
MODE_DETECT additions

### ISSUE THREAD

**Issue by 40wattrange** [retrospy/RetroSpy#206]
So a handful of requests to expand support of just one arduino device:

1) The Arduino Nano has analog pins A0-A7 - would it be possible to get the additional analog pins supported rather than limiting it to the A0-A5 of the full?

<strike>2) To get another "slot" in MODE_DETECT, can we get a bootup config on a value of null? Essentially if no analog pins are grounded, boot a specific config. This could act as a "default" state, so it free's up another pin for assignment.</strike>

3) This is just bonus - if you were to make a declarable null value - aka "default" state - within MODE_DETECT as mentioned in #2 - you could make it so there is no difference between mode_detect and normal modes - mode_detect could always be on - and then just declare the null state only if you want to do a single system flash. This could simplify the config of mode_detect for people since you would just declare:

**Comment by zoggins** [comment]
Yeah I can add the extra pins.  There is already a default state.  In the default MODE_DETECT code the else condition (i.e. NES) is chosen if no analog pin is grounded.  and I can probably make 3 work.

**Comment by 40wattrange** [comment]
oh dang, ok. I need to dive deeper on the mode_detect stuff. It seems to have changed since i last used it.

**Comment by zoggins** [comment]
Also while not convenient when using a jumper wire you could theoretically use short multiple analog inputs and treat it as a binary number further expanding the number of consoles you could load at once.

**Comment by 40wattrange** [comment]
That was something I was going to bring up further, if need be :)

At this time having 8 slots, and another "else" slot is more than enough for me and what im currently doing :)
