### ISSUE TITLE
RS Crashes when your skin declares generic w/ other types.

### ISSUE THREAD

**Issue by 40wattrange** [retrospy/RetroSpy#207]
When I attempt to put the type "generic" in addition to other types, the application crashes instantly - I dont even see it spawn.

Finding conditions:

Had a skin that was set to type="snes,mister" and it worked fine - set type to "snes,mister,generic" and the application wouldnt even launch.

Odd side note - the x86 and x64 exe files would launch, but would not list the skin as generic.

**Comment by zoggins** [comment]
Can I have your skin?  I can repro on my end.

**Comment by 40wattrange** [comment]
For some reason it wouldnt crash again. Probably was wrong punctuation or something up with my machine.
