### ISSUE TITLE
Remember previous arduino selected

### ISSUE THREAD

**Issue by 40wattrange** [retrospy/RetroSpy#253]
Can it be added that RS will remember which Arduino you last used?

I have 2 arduinos hooked up to my machine (port 3 and 4), and always have to adjust to port 4 when starting it up.

**Comment by zoggins** [comment]
I honestly thought I had added that already.  I will make it happen.

**Comment by zoggins** [comment]
Found the bug, will be out in the next release.

**Comment by 40wattrange** [comment]
Awesome! I was pretty sure you had already had this added, but figured it was a bug in the re-write.

**Comment by zoggins** [comment]
This should be fixed in 6.1.1
