### ISSUE TITLE
Issue with Pop!_OS

### ISSUE THREAD

**Issue by FelixHelixTM** [retrospy/RetroSpy#255]
The program itself opens and runs, however, on Pop!_OS 22.04 I am unable to get RetroSpy to detect anything from the COM ports, even after giving the proper user permissions as stated in the guide. While Pop!_OS 22.04 is based off Ubuntu 22.04, I'm unsure if there's something causing a compatibility issue or not, and if RetroSpy simply doesn't work correctly with Pop!_OS, or if it's user error!

**Comment by zoggins** [comment]
You rebooted after permissions?  I will take a look.

**Comment by FelixHelixTM** [comment]
![Screenshot from 2023-02-01 19-18-16](https://user-images.githubusercontent.com/108558974/216199183-4cee3eb0-509c-425e-a9b1-aba9a36c08af.png) I have rebooted, and this is all the appears for me, also, I am using an eletromodder v2. Not sure if that could be causing any issues, but it does work with the windows version.

**Comment by zoggins** [comment]
Try "Options -> Don't Filter COM ports"

**Comment by zoggins** [comment]
I'm installing Pop!_OS right now to see what I can see.

**Comment by FelixHelixTM** [comment]
Okay! I just tried that but still the same result. :(

**Comment by zoggins** [comment]
sudo apt-get remove brltty
reboot

Should fix your problem

**Comment by FelixHelixTM** [comment]
Thank you! It does work now!

**Comment by zoggins** [comment]
I added Pop!_OS to the optional step that says to remove that package.
