### ISSUE TITLE
Bad Interpreter - Cannot Connect

### ISSUE THREAD

**Issue by Chromagram** [retrospy/RetroSpy#256]
Hello,

I've tried following the steps on the site about setting this up on the MiSTer. When I run the update-retrospy.sh script, it has a line that says /tmp/update-retrospy-installer.sh: /bin/bash^M: bad interpreter: No such file or directory.

The line after still says Installation complete. However, no matter how many times I try, the viewer software on Windows will not connect, and it just says "Cannot connect to -MiSTer IP-".

Is there something I'm missing? Only thing I can think of is my PC is connected to Ethernet (which appears in Windows as the same network name as the MiSTer's network) and the MiSTer itself is on Wi-Fi (I don't have a second 15 foot long cable to run across my floor for the MiSTer. However, I did try both on Wi-Fi on the same network and it's the same problem.

**Comment by zoggins** [comment]
The encoding must have gotten messed up when I uploaded it, I will get that fixed.  Do you have SSH enabled on your MiSTer?  The MiSTer code has nothing to do with the required SSH connection that is made.

From: Chroma ***@***.***>
Sent: Monday, February 13, 2023 18:00
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] Bad Interpreter - Cannot Connect (Issue #256)


Hello,

I've tried following the steps on the site about setting this up on the MiSTer. When I run the update-retrospy.sh script, it has a line that says /tmp/update-retrospy-installer.sh: /bin/bash^M: bad interpreter: No such file or directory.

The line after still says Installation complete. However, no matter how many times I try, the viewer software on Windows will not connect, and it just says "Cannot connect to -MiSTer IP-".

Is there something I'm missing? Only thing I can think of is my PC is connected to Ethernet (which appears in Windows as the same network name as the MiSTer's network) and the MiSTer itself is on Wi-Fi (I don't have a second 15 foot long cable to run across my floor for the MiSTer. However, I did try both on Wi-Fi on the same network and it's the same problem.

**Comment by zoggins** [comment]
Also is this the 6.1 release?  Just want to make sure.

From: Chroma ***@***.***>
Sent: Monday, February 13, 2023 18:00
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] Bad Interpreter - Cannot Connect (Issue #256)


Hello,

I've tried following the steps on the site about setting this up on the MiSTer. When I run the update-retrospy.sh script, it has a line that says /tmp/update-retrospy-installer.sh: /bin/bash^M: bad interpreter: No such file or directory.

The line after still says Installation complete. However, no matter how many times I try, the viewer software on Windows will not connect, and it just says "Cannot connect to -MiSTer IP-".

Is there something I'm missing? Only thing I can think of is my PC is connected to Ethernet (which appears in Windows as the same network name as the MiSTer's network) and the MiSTer itself is on Wi-Fi (I don't have a second 15 foot long cable to run across my floor for the MiSTer. However, I did try both on Wi-Fi on the same network and it's the same problem.

**Comment by Chromagram** [comment]
Thanks for the prompt reply :)

Yes, this is the 6.1 version, I picked up the newest release from GitHub directly. I believe SSH is enabled by default on MiSTer? I do use Wi-Fi on MiSTer to FTP files and games onto it.

**Comment by zoggins** [comment]
I will take a look.

**Comment by zoggins** [comment]
Ok the interpreter thing should be fixed now.  I am looking into the connection problem.

**Comment by Chromagram** [comment]
Thank you! Appreciate the help a lot.

**Comment by zoggins** [comment]
The cannot connect is a bug.  Working on a fix now

**Comment by zoggins** [comment]
This should be fixed in 6.1.1

**Comment by Chromagram** [comment]
Can confirm it's up and running. Thanks again for the quick reply and fix!
