### ISSUE TITLE
MiSTer RetroSpy Installer Script Error

### ISSUE THREAD

**Issue by 40wattrange** [retrospy/RetroSpy#262]
The installer is no longer working. I deleted my "retrospy" folder on my MiSTer and ran the download script. Here is the output.

Updating and executing the RetroSpy installer script.

/tmp/update-retrospy-installer.s 100%[========================================================>]     564  --.-KB/s    in 0.001s

/media/fat/Scripts/update-retrospy.sh: /tmp/update-retrospy-installer.sh: /bin/bash^M: bad interpreter: No such file or directory

Installation complete! Please go to http://www.retro-spy.com to download the newest Windows client application.

I've confirmed that /media/fat/retrospy/retrospy is never created - the folder, nor the file.

If this is something you want to fix/change I would suggest looking into the [Downloader ](https://github.com/MiSTer-devel/Downloader_MiSTer/#custom-databases) script by @theypsilon https://github.com/theypsilon and seeing if you can make a db that would link into his script. This way it would check for updates whenever you were to run his script and would probably future proof it.

**Comment by zoggins** [comment]
The encoding of the script keeps getting messed up, it should be fixed now.
