### ISSUE TITLE
N64 shuts off when arduino is plugged in

### ISSUE THREAD

**Issue by SioNisti** [retrospy/RetroSpy#269]
tried this on an arduino uno and some fake nano and neither work.

no controller plugged in = works
controller plugged in = works
controller plugged in through extension cable = works
arduino connected to the pc = doesnt work

the weird thing is that it used to work with the same setup.  the arduino is defintely the culprit but no clue what the problem is.
i have also made a SNES input display which has no problems.

see video.  problem at 2:05
https://www.youtube.com/watch?v=jEsKjfFP0YE

edit: okay now i got it to not shut off but the games are not recognizing the controller if the arduino is plugged in
edit2: i didnt have the red and white plugs of the composite cable plugged in end when i did plug them in the console shut off
edit3: if the data wire is connected to the arduino the controller wont work.

**Comment by zoggins** [comment]
It sounds like you are shorting the power line to GND when plugged into the Arduino. Are you sure you have GND on the left looking at the end of the cable attached to the controller (with the semi circle up)?   Not sure if that is the problem but it definitely sounds like shorting power to ground, which I have done more than once. :)

**Comment by zoggins** [comment]
It might help to send me a pic of your cable end with labels for what you have them wired to

**Comment by SioNisti** [comment]
> It might help to send me a pic of your cable end with labels for what you have them wired to

yeah i should have done that immediatly, i checked the cables multiple times with a multimeter.  ill get a pic for you tomorrow

**Comment by SioNisti** [comment]
sorry for the long wait i got really lazy. 
but here is a picture of the arduino.
![image](https://github.com/retrospy/RetroSpy/assets/38298141/2a0e7e9e-6239-47da-b34e-ffca4cc76575)

and here is a beautiful paint drawing with what color cable corresponds to which "hole" in the cable end.  i tested these with my multimeter so they should be right.
![image](https://github.com/retrospy/RetroSpy/assets/38298141/3c74123d-f45e-46cd-9642-511da4380d16)

the setup in the picture doesnt power off the console but it doesnt get any input from the controller.
![image](https://github.com/retrospy/RetroSpy/assets/38298141/f464fbc8-a690-40eb-96a6-5418fd360e9f)

**Comment by SioNisti** [comment]
okay really weird.  i switched the orange and the black cable (black to ground and orange not connected) and it works BUT not on retrospy. only on nintendo spy.  i also have the same problem with my n64 input display that on retro spy it thinks im holding down all the buttons but nintendo spy works fine.

okay reinstalling retrospy fixed it.  that really weird it did work on this very install with my ps2 input display.

**Comment by zoggins** [comment]
Trying to think why its working in Nintendospy and not retrospy.  What firmware do you have on the Arduino?

**Comment by SioNisti** [comment]
i uploaded the frimware.ino from the broken retrospys firmware folder
