### ISSUE TITLE
Usb adapter not working with RetroSpy

### ISSUE THREAD

**Issue by mbarela82** [retrospy/RetroSpy#271]
I'm using a usb adapter with my Mister and RetroSpy doesn't seem to recognize it. I'm trying to use an NES oem controller and it doesn't show up in the skins. It does work with the SNES skin that is available by default but the A and B buttons are reversed.

The adapter I'm using is the 4dapter by Timville on Tindie.

**Comment by zoggins** [comment]
What source are you using?  The MiSTer one?  Try this one.  Drop it in the skins directory in the RetroSpy folder in program files.  Say yes when it wants to over write.  Let me know if it works.

From: mbarela82 ***@***.***>
Sent: Monday, October 23, 2023 10:42
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] Usb adapter not working with RetroSpy (Issue #271)


I'm using a usb adapter with my Mister and RetroSpy doesn't seem to recognize it. I'm trying to use an NES oem controller and it doesn't show up in the skins. It does work with the SNES skin that is available by default but the A and B buttons are reversed.

The adapter I'm using is the 4dapter by Timville on Tindie.

**Comment by zoggins** [comment]
Found a mistake.  Here is an updated one.

From: mbarela82 ***@***.***>
Sent: Monday, October 23, 2023 10:42
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] Usb adapter not working with RetroSpy (Issue #271)


I'm using a usb adapter with my Mister and RetroSpy doesn't seem to recognize it. I'm trying to use an NES oem controller and it doesn't show up in the skins. It does work with the SNES skin that is available by default but the A and B buttons are reversed.

The adapter I'm using is the 4dapter by Timville on Tindie.

**Comment by zoggins** [comment]
Found another mistake.  Try this one.

From: mbarela82 ***@***.***>
Sent: Monday, October 23, 2023 10:42
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] Usb adapter not working with RetroSpy (Issue #271)


I'm using a usb adapter with my Mister and RetroSpy doesn't seem to recognize it. I'm trying to use an NES oem controller and it doesn't show up in the skins. It does work with the SNES skin that is available by default but the A and B buttons are reversed.

The adapter I'm using is the 4dapter by Timville on Tindie.

**Comment by mbarela82** [comment]
Thank you for your response. I don't see the file on your reply.

**Comment by zoggins** [comment]
[wii-nes_3.zip](https://github.com/retrospy/RetroSpy/files/13078505/wii-nes_3.zip)

**Comment by mbarela82** [comment]
Thank you! I'll try it out and let you know.

**Comment by mbarela82** [comment]
That works! Thank you so much!
