### ISSUE TITLE
N64.cpp typo

### ISSUE THREAD

**Issue by SmolAlli** [retrospy/RetroSpy#283]
https://github.com/retrospy/RetroSpy/blame/45aff70c408ca263304e30cafe0b83a0f2bfbbd0/firmware/sketches/N64.cpp#L341
Is there meant to be a space between `rawData` and `[24]` in `rawData [24] == 0`? doesn't seem right to me

**Comment by zoggins** [comment]
in C++ white space doesn't matter.
