### ISSUE TITLE
Support for Gameboy Interface

### ISSUE THREAD

**Issue by nitrostemp** [retrospy/RetroSpy#61]
would it be possible to add support for inputs thru a gba using GBI?

**Comment by zoggins** [comment]
I am sure it is possible.  I just moved so all my equipment is in boxes, but as soon as I am settled I will take a look.

**Comment by nitrostemp** [comment]
JRP told me this may help you in regards to the gba as a controller communication https://github.com/ExtremsCorner/gba-as-controller/blob/gc/controller/source/si.arm.c

**Comment by zoggins** [comment]
Yeah, I got it working with the offical Gameboy Player software a while back, so I imagine it must be similar.

**Comment by nitrostemp** [comment]
just checking up on this, did you make any progress?

**Comment by zoggins** [comment]
Sorry for the delay.  I moved recently and am finally getting everything
unpacked.  Should be able to get to it this month. Again, sorry for the
delay life has been hectic.

**Comment by zoggins** [comment]
Is there something that wasn't working?  I have use the stock GBA player disc and GBI and the Gameboy Advance works as expected.

**Comment by nitrostemp** [comment]
im asking JRP, as he is the one that requested this; just to check what version of GBI are you using?

**Comment by nitrostemp** [comment]
ok, ive been told that high fidelity might be different, attached is some context from JRP.
![image](https://user-images.githubusercontent.com/39111880/59333379-88401a00-8d3b-11e9-8453-8f97c896baea.png)

**Comment by zoggins** [comment]
Not sure what version of GBI I have, it's older though, but with the 3.0
firmware and viewer gbihf works as expected. I will update GBI tonight to
the newest version and check that.

**Comment by zoggins** [comment]
Just came home and checked.  Newest version of everything (UI, firmware and GBI) all seems to work great.

**Comment by nitrostemp** [comment]
can you confirm it works with "gbihf.dol"

**Comment by nitrostemp** [comment]
and im double checking, this is connecting a gba via the link cable to play..

**Comment by zoggins** [comment]
Gbihf works this is via a gba hooked up via link cable to the second
joystick port

**Comment by zoggins** [comment]
Ok that post was bad, it made no sense. :)
Ok, I test the newest version of gbi.dol and gbihr.dol (i did not test gbisr.dol because I forgot).
I was using an original Gameboy Advance hooked up to controller port 2 with a link cable.
Everything appeared to work correctly on the Everdrive menu and a GBA few games I started up.
