### ISSUE TITLE
Flicker and shadow input on nano

### ISSUE THREAD

**Issue by krusherpt** [retrospy/RetroSpy#66]
So I'm having problems with my arduino nano clone and retrospy on my snes.
I already rechecked my soldering and wiring but still having flickering and shadow input, using the old nintendospy firmware I have less flicker or shadow input, I'm using an extension for the wiring.
Can anyone help me please?

**Comment by zoggins** [comment]
What version of the firmware are you using? You are just straight using
MODE_NES?  I am here to help, but on vacation with limited internet until
Tuesday.

**Comment by krusherpt** [comment]
Im using MODE_SNES and thanks for the help.

**Comment by krusherpt** [comment]
Also I edited the original post so, the freeze was from the game, nothing to do with the retrospy (when I die theres no input registering)

**Comment by zoggins** [comment]
I have never used a nano, are you using the unmodified firmware on the
nano? Usually flickering/shadow inputs are due to interrupts not being
disabled when reading the controller, but they are off to SNES.

**Comment by krusherpt** [comment]
yes  im using it unmodified, since the pinout and specs are the "same", I'm no expert on arduinos but the only thing that improved the situation was the 2014 nintendospy firmware, but still had flickers and shadow input.

**Comment by zoggins** [comment]
Also exactly what board are you using, I can pick one up to see if I can
reproduce it

**Comment by krusherpt** [comment]
Nano V3.0 Mini USB ATmega328 5V 16MHz Micro-Controller CH340G Driver For Arduino

**Comment by zoggins** [comment]
Board ordered, will figure it out

**Comment by zoggins** [comment]
I got the board and I cannot repro.  It seems to work great for me.  I used the ATMega382P (Old bootloader) to upload and it just works.  Is there a particular game you were seeing it, more than others?

**Comment by edru** [comment]
Ive made numerous nano devices at this point and have seen no issues myself.

**Comment by zoggins** [comment]
One case where i see this is when Arduino GND isn't connected to the controller GND, but I have no idea if that is the case here.  There is also another bug oN SNES about flickering when CPU is under heavy usage.
