### ISSUE TITLE
Xbox 360 Startup is super picky

### ISSUE THREAD

**Issue by zoggins** [retrospy/RetroSpy#92]

**Comment by fatihG** [comment]
I just ordered a BeagleBone Black board, specifically for the 360. 

Since this was opened in 2019 and recently updated back in December, will this be 'fixed'?

The instructions say that it works '90%' of the time if you follow the startup sequence. 
But was just wondering if there was work planned to make this more seamless.

**Comment by zoggins** [comment]
It is on my list to revisit soon.  Just need to get some time to dive in.

**Comment by zoggins** [comment]
Actually I am hoping to release a version with improved 360 support in the next couple of days.  Its still not perfect, but its less of a pain in the butt to get going.  Currently ethernet is the only way because there is too much data for the serial communication to handle.

**Comment by TheDrinkingBird** [comment]
Thank you for your informative and speedy reply! Hope things go well.

**Comment by zoggins** [comment]
I am going to release the update tomorrow.  The  beaglebone will require a reimage and the new hostname will be retrospy.local.  The way to get the 360 to work is start everything up, but leave the controller unplugged.  Once the view window comes up (you are looking at the image of the controller) plug in the controller and do not touch any of the buttons or stick until the green light is solid on the controller.  If the controller does work on the Xbox, close the view window and unplug the controller.  Try again.  This can take 4 or 5 times, which sucks, but this doesn't require all the get lucky timing the old method had.\

**Comment by TheDrinkingBird** [comment]
I know this has to be very hard and tedious, so thank you for all of your work!

**Comment by TheDrinkingBird** [comment]
Hey Zoggins, I reimaged my sd card, reflashed the BB, followed the instructions in your last comment to the best of my understanding, yet I can't seem to get it working. 1. plug in BB USB & xbox 360 2. start up retro spy (hostname: retrospy.local) & hit go 3. wait for input view window (picture of controller appears) then plug in controller 4. don't press a button until the green light has stopped blinking. Is that correct?

**Comment by zoggins** [comment]
You tried 4 or 5 times and still nothing? What controller and console version?
________________________________

**Comment by zoggins** [comment]
Also what the symptoms? RetroSpy shows inputs, but no controller activity on the Xbox?
________________________________

**Comment by TheDrinkingBird** [comment]
I've tried at least 20 times. I have a white wired xbox 360 controller for windows (I customized its appearance, but no modifications), I'll try to send a picture. It's a black xbox s. Console Serial Number: 068340703808 & Console ID: 026791782282. I will also send a picture of the xbox. My symptoms: RetroSpy shows inputs no problem, but no controller activity on xbox. Thank you for the help again! 

![IMG_9702](https://user-images.githubusercontent.com/123955665/217689519-186084aa-1489-4136-9619-3cc6066891db.jpg)

![IMG_9701](https://user-images.githubusercontent.com/123955665/217689541-30ee9a55-ba15-4225-b84d-9955c1c64f20.jpg)

![IMG_9700](https://user-images.githubusercontent.com/123955665/217689619-76e02fe0-4584-4f6d-b69d-0374621e42f5.jpg)

![IMG_9698](https://user-images.githubusercontent.com/123955665/217689641-e9a9a3d9-79cf-4f45-912e-a1fcad7537fe.jpg)

![IMG_9699](https://user-images.githubusercontent.com/123955665/217689677-5be484ee-0410-4965-9a39-d022e71ba8d8.jpg)

**Comment by zoggins** [comment]
I have two of the same Xboxs, and I just got a black OEM controller.  I have been testing on a 3rd party controller.  I will see if I have the same problem with the new controller.

**Comment by zoggins** [comment]
Also what version of the UI are you using and on what OS?

**Comment by zoggins** [comment]
Also is the Xbox 360 modded at all? I have one modded and one not modded, just trying to simulate the best I can.

**Comment by TheDrinkingBird** [comment]
My Xbox is Not modded at all. xbox Dashboard: 2.0.17559.0 & Windows 10 Home. Version: 21H2. OS Build: 19044.2486. 64-bit operating system.

![IMG_9704](https://user-images.githubusercontent.com/123955665/217870523-3bdde83d-1df6-49d4-a28d-3be34d3ace85.jpg)

**Comment by zoggins** [comment]
This is a video of my process for getting working on my 360.

https://retrospycom-my.sharepoint.com/:v:/g/personal/zoggins_retro-spy_com/EUjbfO7MJPZDvFUmsbu47MUB6Dv8V2wDBHET97zE73Dknw?e=OMC5L7

**Comment by TheDrinkingBird** [comment]
[https://youtu.be/1DjVZyla61w](url)

**Comment by TheDrinkingBird** [comment]
https://youtu.be/1DjVZyla61w

**Comment by zoggins** [comment]
Let me put together a debugging program that will let me see where it is failing.  I am hoping I can get it done tonight, but might be tomorrow morning.  Sorry for the headache.

**Comment by TheDrinkingBird** [comment]
No worries! I can't wait to find out it was me doing one tiny thing wrong this whole time!

**Comment by zoggins** [comment]
Inside the zip file (linked) run UsbUpdater.exe instead of RetroSpy.  Once it connects plug in the controller.  Copy the output and send it my way.  Its a little hacky, sorry.

https://retrospycom-my.sharepoint.com/:u:/g/personal/zoggins_retro-spy_com/ERRKuSjf22BMkDhZk6a4uiwBvpKYPXjvNoDL0AaAwg9SYQ?e=3lvIYY

**Comment by TheDrinkingBird** [comment]
Plug in the controller to the BeagleBone? do I need to turn on the xbox? Sorry if the file explains itself, haven't downloaded yet

**Comment by zoggins** [comment]
Do everything like you normally, just use usbupdat er in the zip file instead of retrospy
________________________________

**Comment by TheDrinkingBird** [comment]
[RetroSpy USB Updater.txt](https://github.com/retrospy/RetroSpy/files/10708637/RetroSpy.USB.Updater.txt)

**Comment by zoggins** [comment]
Do you have any other USB devices plugged into the 360?

**Comment by TheDrinkingBird** [comment]
No, only the beaglebone

**Comment by zoggins** [comment]
The xbox is connected to the network via an ethernet cable?  Or not connected at all?  Just trying figure out why we have completely different behaviors for the same setup, lol.

**Comment by TheDrinkingBird** [comment]
My Xbox is Not connected with an ethernet cable

**Comment by zoggins** [comment]
Can I see the label of the back of your controller?

**Comment by zoggins** [comment]
Also what is the MFG date on the back of the Xbox?

**Comment by zoggins** [comment]
Re-download the zip file and run UsbUpdater with the controller already plugged in and send the output.

**Comment by TheDrinkingBird** [comment]
Lmk if these pictures don't come through. I'm about to try your last message

![Uploading usetldr_2095310_u_2129623_image_format_rkFJXVgFHdNwVjl.jpg…]()

![usetldr_2095310_u_2129623_image_format_okUTFGEFvQnWeSo](https://user-images.githubusercontent.com/123955665/218181414-7095f1eb-244a-4021-bd33-48a08adc7711.jpg)

![Uploading usetldr_2095310_u_2129623_image_format_rkFJXVgFHdNwVjl.jpg…]()

![usetldr_nw_image_format_yEaaOCYOcTSKDUM](https://user-images.githubusercontent.com/123955665/218181098-34876d0e-5511-4252-bb64-27a9d372465f.jpg)

**Comment by TheDrinkingBird** [comment]
It gets stuck on (Not Responding). I re-downloaded the zip file and plugged in the controller before I ran the program 

![Screenshot (182)](https://user-images.githubusercontent.com/123955665/218188734-b36f0b17-5a5d-4e66-8c7a-3ec89e836134.png)

**Comment by zoggins** [comment]
hmmm, that isn't what I wanted.  let me send a new link

**Comment by zoggins** [comment]
https://retrospycom-my.sharepoint.com/:u:/g/personal/zoggins_retro-spy_com/EZXi32nOCadIiUasJx4nYpQB3hjkNpwnHZfWBbv8yyhOyg?e=PLYnav

**Comment by TheDrinkingBird** [comment]
I don't see USB Updater in this new Zip file, run on retrospy?

**Comment by zoggins** [comment]
there isn't a usbupdater.exe?

**Comment by TheDrinkingBird** [comment]
![usetldr_nw_image_format_GTfXmQJsGTrmLVJ](https://user-images.githubusercontent.com/123955665/218203271-4cf418c7-e7a6-40dd-bb25-2ccd6216614f.jpg)

![Uploading usetldr_2095310_u_2129623_image_format_cyhvDbEwVGTWwwd.jpg…]()

![Uploading usetldr_2095310_u_2129623_image_format_YgVnnPvdjuwIkEm.jpg…]()

![Uploading usetldr_2095310_u_2129623_image_format_yMyiiAyPcMJNaVA.jpg…]()

**Comment by TheDrinkingBird** [comment]
WinRar gave me this message, so I used BreeZip to extract it.

**Comment by zoggins** [comment]
https://retrospycom-my.sharepoint.com/:u:/g/personal/zoggins_retro-spy_com/EaGFdiizhvpMo88TJxQhwHMBkLrD707owTtPtkfZ6SeKZQ?e=5goVej

**Comment by TheDrinkingBird** [comment]
I'll get back to you tomorrow morning with my results

**Comment by TheDrinkingBird** [comment]
![Screenshot (187)](https://user-images.githubusercontent.com/123955665/218266275-876fd75d-6cf3-40ab-8705-71ed48b2c056.png)

![Screenshot (188)](https://user-images.githubusercontent.com/123955665/218266287-d136ce34-a56e-4627-ab0f-c0772e0165ff.png)

**Comment by TheDrinkingBird** [comment]
It gives me this message when I try to run UsbUpdater. Downloaded .NET Desktop Runtime, still won't open

**Comment by TheDrinkingBird** [comment]
Thank you for going this in-depth, really appreciate it!

**Comment by TheDrinkingBird** [comment]
Thank you for going this in-depth, really appreciate it!

**Comment by TheDrinkingBird** [comment]
Hey Zoggins, any luck with the xbox 360 controller?

**Comment by zoggins** [comment]
I got the exact controller of Ebay.  It just got here, so still working on it.

**Comment by zoggins** [comment]
Do you have the box your controller came in?  if so what is the serial number on the bottom of the box?

**Comment by zoggins** [comment]
I had a breakthrough.  I think I have it working doing some more testing.  The long story short is that I am pretty sure these controllers are not 100% legit and they some dodgy stuff around the controller authentication process, so I had to kinda patch up the authentication process.

**Comment by zoggins** [comment]
I have checked in the change.  Its not in the image yet.  The Vision USB updater should pull it down though if you want it early.

**Comment by TheDrinkingBird** [comment]
![Uploading usetldr_nw_image_format_pbbncrDZeCEwJgi.jpg…]()

**Comment by TheDrinkingBird** [comment]
lmk if you can't see the picture,

**Comment by TheDrinkingBird** [comment]
![usetldr_nw_image_format_pbbncrDZeCEwJgi](https://user-images.githubusercontent.com/123955665/228891342-bcc4fe99-6f2f-4db3-aaeb-9bbbe1f55274.jpg)

**Comment by zoggins** [comment]
This should be fixed in the new firmware
